version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(rust): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(elixir): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(nix): "
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
