name: Rust CI
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  check:
    name: Run Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1
      - run: make rust-check

  formatted:
    name: Check Formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1
      - run: make rust-formatted

  lints:
    name: Run clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1
      - run: make rust-lint
